.TH "lib/old_libs Directory Reference" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/old_libs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanalyze_beatEstimation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_beatEstimation\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_128\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_128\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_2048\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_2048\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_256\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_frameEnergy_256\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_odf\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_odf\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_peakdetect\&.h\fP"
.br
.ti -1c
.RI "file \fBanalyze_peaks\&.cpp\fP"
.br
.ti -1c
.RI "file \fBanalyze_peaks\&.h\fP"
.br
.ti -1c
.RI "file \fBAudio\&.h\fP"
.br
.ti -1c
.RI "file \fBodf\&.cpp\fP"
.br
.ti -1c
.RI "file \fBodf\&.h\fP"
.br
.ti -1c
.RI "file \fBonset_detection\&.cpp\fP"
.br
.ti -1c
.RI "file \fBonset_detection\&.h\fP"
.br
.ti -1c
.RI "file \fBonset_detection_128\&.cpp\fP"
.br
.ti -1c
.RI "file \fBonset_detection_128\&.h\fP"
.br
.ti -1c
.RI "file \fBpeaks\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpeaks\&.h\fP"
.br
.in -1c
