.TH "testing src Directory Reference" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBeat_Detection2020\&.ino\fP"
.br
.ti -1c
.RI "file \fBbounce\&.ino\fP"
.br
.ti -1c
.RI "file \fBbuffer test\&.ino\fP"
.br
.ti -1c
.RI "file \fBfade LED\&.ino\fP"
.br
.ti -1c
.RI "file \fBmagnet test org\&.ino\fP"
.br
.ti -1c
.RI "file \fBmagnet test\&.ino\fP"
.br
.ti -1c
.RI "file \fBRGB LED test\&.ino\fP"
.br
.ti -1c
.RI "file \fBRGB test\&.ino\fP"
.br
.ti -1c
.RI "file \fBtiming led test\&.ino\fP"
.br
.in -1c
