.TH "lib/old_libs/analyze_frameEnergy_256.h" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/old_libs/analyze_frameEnergy_256.h
.SH SYNOPSIS
.br
.PP
\fC#include 'core_pins\&.h'\fP
.br
\fC#include 'AudioStream\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioAnalyzeFrameEnergy256\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
