.TH "AudioAnalysisODF" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalysisODF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <odf\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalysisODF\fP (void)"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBdeltaE\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file odf\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalysisODF::AudioAnalysisODF (void)\fC [inline]\fP"

.PP
Definition at line 36 of file odf\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AudioAnalysisODF::available ()\fC [inline]\fP"

.PP
Definition at line 38 of file odf\&.h\&.
.SS "uint32_t AudioAnalysisODF::deltaE (void)"

.PP
Definition at line 170 of file odf\&.cpp\&.
.SS "void AudioAnalysisODF::update (void)\fC [virtual]\fP"

.PP
Definition at line 50 of file odf\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
