.TH "AudioPeak" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioPeak
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_peakdetect\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioPeak\fP (void)"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "void \fBbegin\fP (bool noReset)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.ti -1c
.RI "uint16_t \fBDpp\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file analyze_peakdetect\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioPeak::AudioPeak (void)\fC [inline]\fP"

.PP
Definition at line 34 of file analyze_peakdetect\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void AudioPeak::begin (bool noReset)"

.SS "void AudioPeak::begin (void)\fC [inline]\fP"

.PP
Definition at line 39 of file analyze_peakdetect\&.h\&.
.SS "uint16_t AudioPeak::Dpp (void)"

.SS "void AudioPeak::stop (void)\fC [inline]\fP"

.PP
Definition at line 40 of file analyze_peakdetect\&.h\&.
.SS "virtual void AudioPeak::update (void)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
