.TH "AudioAnalyzeBeatEstimation" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalyzeBeatEstimation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_beatEstimation\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalyzeBeatEstimation\fP (void)"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBac\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file analyze_beatEstimation\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalyzeBeatEstimation::AudioAnalyzeBeatEstimation (void)\fC [inline]\fP"

.PP
Definition at line 36 of file analyze_beatEstimation\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t AudioAnalyzeBeatEstimation::ac (void)"

.PP
Definition at line 202 of file analyze_beatEstimation\&.cpp\&.
.SS "bool AudioAnalyzeBeatEstimation::available ()\fC [inline]\fP"

.PP
Definition at line 37 of file analyze_beatEstimation\&.h\&.
.SS "void AudioAnalyzeBeatEstimation::update (void)\fC [virtual]\fP"

.PP
Definition at line 64 of file analyze_beatEstimation\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
