.TH "AudioAnalyzePeaks" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalyzePeaks
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_peaks\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalyzePeaks\fP (void)"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBgetPeak\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBODF\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file analyze_peaks\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalyzePeaks::AudioAnalyzePeaks (void)\fC [inline]\fP"

.PP
Definition at line 36 of file analyze_peaks\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AudioAnalyzePeaks::available ()\fC [inline]\fP"

.PP
Definition at line 37 of file analyze_peaks\&.h\&.
.SS "uint32_t AudioAnalyzePeaks::getPeak (void)"

.PP
Definition at line 243 of file analyze_peaks\&.cpp\&.
.SS "uint32_t AudioAnalyzePeaks::ODF (void)"

.PP
Definition at line 246 of file analyze_peaks\&.cpp\&.
.SS "void AudioAnalyzePeaks::update (void)\fC [virtual]\fP"

.PP
Definition at line 63 of file analyze_peaks\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
