.TH "AudioAnalyzeFrameEnergy128" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalyzeFrameEnergy128
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_frameEnergy_128\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalyzeFrameEnergy128\fP (void)"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "void \fBbegin\fP (bool noReset)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBSum\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file analyze_frameEnergy_128\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalyzeFrameEnergy128::AudioAnalyzeFrameEnergy128 (void)\fC [inline]\fP"

.PP
Definition at line 36 of file analyze_frameEnergy_128\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void AudioAnalyzeFrameEnergy128::begin (bool noReset)"

.PP
Definition at line 52 of file analyze_frameEnergy_128\&.cpp\&.
.SS "void AudioAnalyzeFrameEnergy128::begin (void)\fC [inline]\fP"

.PP
Definition at line 41 of file analyze_frameEnergy_128\&.h\&.
.SS "void AudioAnalyzeFrameEnergy128::stop (void)\fC [inline]\fP"

.PP
Definition at line 42 of file analyze_frameEnergy_128\&.h\&.
.SS "uint32_t AudioAnalyzeFrameEnergy128::Sum (void)"

.PP
Definition at line 56 of file analyze_frameEnergy_128\&.cpp\&.
.SS "void AudioAnalyzeFrameEnergy128::update (void)\fC [virtual]\fP"

.PP
Definition at line 31 of file analyze_frameEnergy_128\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
