.TH "AudioAnalyzeFrameEnergy2048" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalyzeFrameEnergy2048
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_frameEnergy_2048\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalyzeFrameEnergy2048\fP (void)"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "void \fBbegin\fP (bool noReset)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBSum\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file analyze_frameEnergy_2048\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalyzeFrameEnergy2048::AudioAnalyzeFrameEnergy2048 (void)\fC [inline]\fP"

.PP
Definition at line 36 of file analyze_frameEnergy_2048\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void AudioAnalyzeFrameEnergy2048::begin (bool noReset)"

.PP
Definition at line 157 of file analyze_frameEnergy_2048\&.cpp\&.
.SS "void AudioAnalyzeFrameEnergy2048::begin (void)\fC [inline]\fP"

.PP
Definition at line 40 of file analyze_frameEnergy_2048\&.h\&.
.SS "void AudioAnalyzeFrameEnergy2048::stop (void)\fC [inline]\fP"

.PP
Definition at line 41 of file analyze_frameEnergy_2048\&.h\&.
.SS "uint32_t AudioAnalyzeFrameEnergy2048::Sum (void)"

.PP
Definition at line 161 of file analyze_frameEnergy_2048\&.cpp\&.
.SS "void AudioAnalyzeFrameEnergy2048::update (void)\fC [virtual]\fP"

.PP
Definition at line 39 of file analyze_frameEnergy_2048\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
