.TH "AudioAnalyzeODF" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalyzeODF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyze_odf\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalyzeODF\fP (void)"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBdeltaE\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file analyze_odf\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalyzeODF::AudioAnalyzeODF (void)\fC [inline]\fP"

.PP
Definition at line 37 of file analyze_odf\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AudioAnalyzeODF::available ()\fC [inline]\fP"

.PP
Definition at line 39 of file analyze_odf\&.h\&.
.SS "uint32_t AudioAnalyzeODF::deltaE (void)"

.PP
Definition at line 179 of file analyze_odf\&.cpp\&.
.SS "void AudioAnalyzeODF::update (void)\fC [virtual]\fP"

.PP
Definition at line 57 of file analyze_odf\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
