.TH "AudioAnalysisFrameEnergy128" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalysisFrameEnergy128
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <onset_detection_128\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalysisFrameEnergy128\fP (void)"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "void \fBbegin\fP (bool noReset)"
.br
.ti -1c
.RI "void \fBbegin\fP (void)"
.br
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBSum\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file onset_detection_128\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalysisFrameEnergy128::AudioAnalysisFrameEnergy128 (void)\fC [inline]\fP"

.PP
Definition at line 35 of file onset_detection_128\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void AudioAnalysisFrameEnergy128::begin (bool noReset)"

.PP
Definition at line 51 of file onset_detection_128\&.cpp\&.
.SS "void AudioAnalysisFrameEnergy128::begin (void)\fC [inline]\fP"

.PP
Definition at line 40 of file onset_detection_128\&.h\&.
.SS "void AudioAnalysisFrameEnergy128::stop (void)\fC [inline]\fP"

.PP
Definition at line 41 of file onset_detection_128\&.h\&.
.SS "uint32_t AudioAnalysisFrameEnergy128::Sum (void)"

.PP
Definition at line 58 of file onset_detection_128\&.cpp\&.
.SS "void AudioAnalysisFrameEnergy128::update (void)\fC [virtual]\fP"

.PP
Definition at line 30 of file onset_detection_128\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
