.TH "AudioAnalysisFrameEnergy" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioAnalysisFrameEnergy
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <onset_detection\&.h>\fP
.PP
Inherits AudioStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioAnalysisFrameEnergy\fP (void)"
.br
.ti -1c
.RI "bool \fBavailable\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBE\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file onset_detection\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AudioAnalysisFrameEnergy::AudioAnalysisFrameEnergy (void)\fC [inline]\fP"

.PP
Definition at line 36 of file onset_detection\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AudioAnalysisFrameEnergy::available ()\fC [inline]\fP"

.PP
Definition at line 38 of file onset_detection\&.h\&.
.SS "uint32_t AudioAnalysisFrameEnergy::E (void)"

.PP
Definition at line 160 of file onset_detection\&.cpp\&.
.SS "void AudioAnalysisFrameEnergy::update (void)\fC [virtual]\fP"

.PP
Definition at line 44 of file onset_detection\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t AudioAnalysisFrameEnergy::state"

.PP
Definition at line 47 of file onset_detection\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
