.TH "md__r_e_a_d_m_e" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- hyperwiper 
Basic idea is that most normal songs have a consistent (or at least slowly changing) rhythm that can be used as a “click track” for dancers, including robotic windshield wipers\&. By hiding the sound of wipers in the rhythm (a kind of masking), cabin signal-noise ratio can be enhanced\&. Many car drivers and riders enjoy listening to music while driving, and support of cross-modal, synaesthetic stimulus can enhance that experience, a kind of visual music\&.
.PP
Data flow: audio source such as music player or smartphone connected to beat detector as embedded 
