.TH "lib/old_libs/onset_detection.cpp" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/old_libs/onset_detection.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'onset_detection\&.h'\fP
.br
\fC#include 'arm_math\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
