.TH "docs/Pins on prototype (2015) board.txt" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/Pins on prototype (2015) board.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Software Audio \fBSCL\fP (other I2C chips) Volume Pot 15(A1) 15(A1) \- SD Card 10"
.br
.ti -1c
.RI "Software Audio \fBSCK\fP (other SPI chips) Memory Chip 6 = 4"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Software \fBpins\fP"
.br
.ti -1c
.RI "Software Audio \fBControl\fP"
.br
.ti -1c
.RI "Software Audio \fBSDA\fP"
.br
.ti -1c
.RI "Software Audio \fBMOSI\fP"
.br
.ti -1c
.RI "Software Audio \fBMISO\fP"
.br
.ti -1c
.RI "int \fBmagnetPin\fP = 5"
.br
.ti -1c
.RI "int \fBledRedPin\fP = 6"
.br
.ti -1c
.RI "int \fBledGreenPin\fP = 2"
.br
.ti -1c
.RI "const int \fBJOY_A_PIN\fP = 15"
.br
.ti -1c
.RI "const int \fBJOY_B_PIN\fP = 16"
.br
.ti -1c
.RI "const int \fBJOY_C_PIN\fP = 17"
.br
.ti -1c
.RI "const int \fBJOY_D_PIN\fP = 20"
.br
.ti -1c
.RI "const int \fBJOY_E_PIN\fP = 2"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Software Audio SCK (other SPI chips) = 4"

.SS "Software Audio SCL (other I2C chips)"

.SH "Variable Documentation"
.PP 
.SS "Software Audio Control"

.PP
Definition at line 23 of file Pins on prototype (2015) board\&.txt\&.
.SS "const int JOY_A_PIN = 15"

.PP
Definition at line 42 of file Pins on prototype (2015) board\&.txt\&.
.SS "const int JOY_B_PIN = 16"

.PP
Definition at line 43 of file Pins on prototype (2015) board\&.txt\&.
.SS "const int JOY_C_PIN = 17"

.PP
Definition at line 44 of file Pins on prototype (2015) board\&.txt\&.
.SS "const int JOY_D_PIN = 20"

.PP
Definition at line 45 of file Pins on prototype (2015) board\&.txt\&.
.SS "const int JOY_E_PIN = 2"

.PP
Definition at line 46 of file Pins on prototype (2015) board\&.txt\&.
.SS "int ledGreenPin = 2"

.PP
Definition at line 39 of file Pins on prototype (2015) board\&.txt\&.
.SS "int ledRedPin = 6"

.PP
Definition at line 37 of file Pins on prototype (2015) board\&.txt\&.
.SS "int magnetPin = 5"

.PP
Definition at line 36 of file Pins on prototype (2015) board\&.txt\&.
.SS "Software Audio MISO"

.PP
Definition at line 28 of file Pins on prototype (2015) board\&.txt\&.
.SS "Software Audio MOSI"

.PP
Definition at line 28 of file Pins on prototype (2015) board\&.txt\&.
.SS "Software pins"

.PP
Definition at line 23 of file Pins on prototype (2015) board\&.txt\&.
.SS "Software Audio SDA"

.PP
Definition at line 24 of file Pins on prototype (2015) board\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
