.TH "lib/RGB_LED/RGBLED.h" 3 "Sat Mar 12 2022" "HypwerWiper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/RGB_LED/RGBLED.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRGBLED\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcommon_type\fP { \fBCOMMON_CATHODE\fP = 0, \fBCOMMON_ANODE\fP = 1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBcommon_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOMMON_CATHODE \fP\fP
.TP
\fB\fICOMMON_ANODE \fP\fP
.PP
Definition at line 38 of file RGBLED\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HypwerWiper from the source code\&.
